### ISSUE TITLE
Search Engine Api Research

### ISSUE THREAD

**Issue by davidVillarreal03** [davidVillarreal03/Super-Team-Project#6]
## User Story
As a tourist of San Antonio
I want to use this website to get an idea of what to do in the city
so that I can easily navigate San Antonio knowing what I am going to do today

## Acceptance Criteria 
GIVEN I see suggested activities from locals within San Antonio
WHEN I click/tap the search bar 
THEN I can insert the place I found to be interesting

**Comment by Ericameowzers** [comment]
Hey fixed the issues I'll this uploaded for you guys next session. Sorry it
took me so long! Crazy week!! And we just wanted the maps to find the
places correct? Because that's what I did.
